### ISSUE TITLE
Need Help Running Code - Hydra Path Issue on Mac with M-Series Chip

### ISSUE THREAD

**Issue by wyy511511** [IFICL/images-that-sound#1]
Hi,
Sorry for stupid question.

I'm encountering an issue while trying to run the code. I get the following error message:

```
 File "/opt/anaconda3/envs/soundify/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 799, in config_not_found_error
    raise MissingConfigException(
hydra.errors.MissingConfigException: In 'hydra/config': Could not find 'hydra/job_logging/colorlog'

Available options in 'hydra/job_logging':
	default
	disabled
	none
	stdout
Config search path:
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=file:///Users/username/Downloads/images-that-sound/configs/main_imprint
	provider=schema, path=structured:/
```

I am not sure your suggestion that “To create images that sound using our proposed imprint baseline method, run the code with config files **under configs/main_imprint/experiment:**”

 I checked config file exists in the path indicated in this line of code.  `@hydra.main(version_base="1.3", config_path="../configs/main_imprint", config_name="main.yaml")` 

I run the command  `python src/main_imprint.py experiment=examples/bell` in the root dir of the project. 

Also, could you clarify can I run it on personal M-chip Mac? I saw pytorch-cuda in conda environment.yaml.  I also found some code provide alternatives with cpu. Some requires `cuda`. 

 Additionally, if you could specify which tasks are possible to run with a Mac M-Series chip, that would be extremely helpful.

As a side note, I previously saw a video on Bilibili where mountain shapes were used to create music with ancient Chinese instruments. It was really impressive (sorry, I couldn't find the video link). I believe your project could achieve a similar effect. I suspect there might be a way to introduce specific instrument styles when generating audio. If you have read any related works, I would like to hear about them.

Thank you for your help!

**Comment by IFICL** [comment]
Hi, all my codes are tested with Ubuntu and Linux systems, and they work normally. I am not sure if it's possible to run on the Mac M-chip since you might not be able to install those dependent packages.

**Comment by mohamed10555** [comment]
> Hi, Sorry for stupid question.
> 
> I'm encountering an issue while trying to run the code. I get the following error message:
> 
> ```
>  File "/opt/anaconda3/envs/soundify/lib/python3.10/site-packages/hydra/_internal/defaults_list.py", line 799, in config_not_found_error
>     raise MissingConfigException(
> hydra.errors.MissingConfigException: In 'hydra/config': Could not find 'hydra/job_logging/colorlog'
> 
> Available options in 'hydra/job_logging':
> 	default
> 	disabled
> 	none
> 	stdout
> Config search path:
> 	provider=hydra, path=pkg://hydra.conf
> 	provider=main, path=file:///Users/username/Downloads/images-that-sound/configs/main_imprint
> 	provider=schema, path=structured:/
> ```
> 
> I am not sure your suggestion that “To create images that sound using our proposed imprint baseline method, run the code with config files **under configs/main_imprint/experiment:**”
> 
> I checked config file exists in the path indicated in this line of code. `@hydra.main(version_base="1.3", config_path="../configs/main_imprint", config_name="main.yaml")`
> 
> I run the command `python src/main_imprint.py experiment=examples/bell` in the root dir of the project.
> 
> Also, could you clarify can I run it on personal M-chip Mac? I saw pytorch-cuda in conda environment.yaml. I also found some code provide alternatives with cpu. Some requires `cuda`.
> 
> Additionally, if you could specify which tasks are possible to run with a Mac M-Series chip, that would be extremely helpful.
> 
> As a side note, I previously saw a video on Bilibili where mountain shapes were used to create music with ancient Chinese instruments. It was really impressive (sorry, I couldn't find the video link). I believe your project could achieve a similar effect. I suspect there might be a way to introduce specific instrument styles when generating audio. If you have read any related works, I would like to hear about them.
> 
> Thank you for your help!

I have the same issue, did you manage to find a fix? I am running a linux system

**Comment by IFICL** [comment]
@mohamed10555 Can you describe your issue in more detail? Do you have trouble running all three main scripts or just the imprint baseline? All my codes should be able to run **after installing our conda environment**.

**Comment by IFICL** [comment]
@wyy511511 Hi, Yaoyao. I double-checked the traceback you provided. It seems to be the log configuration of hydra. If you install the package of `hydra-colorlog` which should go through. Also you can set to none as well.
